### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by bhi** [arthurflor23/handwritten-text-recognition#11]
I am getting this error when trying to train the model with the bentham dataset.   
Any Ideas why?

Thanks 
Danny Haggard

Traceback (most recent call last):
  File "c:\Users\Danny\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "c:\Users\Danny\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\Danny\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\ProgramData\Anaconda3\envs\Tensorflow\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\ProgramData\Anaconda3\envs\Tensorflow\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\ProgramData\Anaconda3\envs\Tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Danny\Source\Workspaces\Brown Helicopter\TensorFlow\HandwritingReconition\src\main.py", line 155, in <module>
    verbose=1)
  File "c:\Users\Danny\Source\Workspaces\Brown Helicopter\TensorFlow\HandwritingReconition\src\network\model.py", line 173, in fit
    use_multiprocessing=use_multiprocessing, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "C:\ProgramData\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 224, in fit
    distribution_strategy=strategy)
  File "C:\ProgramData\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 547, in _process_training_inputs
    use_multiprocessing=use_multiprocessing)
  File "C:\ProgramData\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 606, in _process_inputs
    use_multiprocessing=use_multiprocessing)
  File "C:\ProgramData\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\data_adapter.py", line 566, in __init__
    reassemble, nested_dtypes, output_shapes=nested_shape)
  File "C:\ProgramData\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 546, in from_generator
    flattened_types = [dtypes.as_dtype(dt) for dt in nest.flatten(output_types)]
  File "C:\ProgramData\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 546, in <listcomp>
    flattened_types = [dtypes.as_dtype(dt) for dt in nest.flatten(output_types)]
  File "C:\ProgramData\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow_core\python\framework\dtypes.py", line 716, in as_dtype
    return _ANY_TO_TF[type_value]
TypeError: unhashable type: 'list'

**Comment by arthurflor23** [comment]
Hello!
Did you run ``--transform`` parameter first? To make bentham.hdf5 file in data folder

**Comment by janru** [comment]
I got the same error when running the tutorial steps in my own python script.
When I tried to run the main.py with some arguments it worked.

**Comment by arthurflor23** [comment]
Hi, guys,
Maybe this [issue](https://github.com/arthurflor23/handwritten-text-recognition/issues/9) can help you. I think the same error was returned.
