### ISSUE TITLE
Error in training the data

### ISSUE THREAD

**Issue by anush97** [arthurflor23/handwritten-text-recognition#19]
Hi, I tried running the training of the data using the command as mentioned in your tutorial :
python main.py --source=Bentham --transform

But it is giving me an error saying:

`Traceback (most recent call last):
  File "C:\Users\hp\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\hp\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\hp\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\hp\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\hp\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 23, in <module>
    from data.generator import DataGenerator, Tokenizer
  File "C:\Users\hp\Desktop\coding\Major Project\work\handwritten-text-recognition-master\src\data\generator.py", line 6, in <module>
    from tensorflow.keras.preprocessing.sequence import pad_sequences
  File "C:\Users\hp\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\hp\Anaconda3\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\hp\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\hp\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\hp\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\hp\Anaconda3\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\hp\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\hp\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\hp\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\hp\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\hp\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\hp\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.`

Can you guide me why am I receiving the same when i have downloaded all the libraries and their versions specified in requirements.txt

**Comment by arthurflor23** [comment]
Hi,
What version of tensorflow does anaconda offer?
From the log error, this module cannot be loaded `` from tensorflow.keras.preprocessing.sequence import pad_sequences`` (line 6) however, this module was added in version 2.0.0+ of TF

**Comment by anush97** [comment]
Hi , in your requirement list you had mentioned tensorflow 2.1 , so it got downloaded and was giving this DLL error. But now when i downgraded it to 2.0 , it worked but gave a different error:

The Bentham dataset will be transformed...
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    ds.read_partitions()
  File "C:\Users\hp\Desktop\coding\Major Project\work\handwritten-text-recognition-master\src\data\reader.py", line 26, in read_partitions
    self.dataset = getattr(self, f"_{self.name}")()
AttributeError: 'Dataset' object has no attribute '_Bentham'

my directory is  as follows:
![p](https://user-images.githubusercontent.com/32952140/77407187-c21a7280-6ddb-11ea-9688-42b5cfe3b2ac.JPG)

**Comment by arthurflor23** [comment]
Hi! The function in reader.py is ``_bentham()``  the error could be this

**Comment by anush97** [comment]
you mean i should run it like this:

python main.py --source=_bentham() --transform

if i do so , :
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    assert os.path.exists(raw_path)
AssertionError

**Comment by arthurflor23** [comment]
Try just ``--source=bentham`` and also rename the folder to ``bentham``

**Comment by anush97** [comment]
hi , thank you for helping me so far.. i wanted to ask isn't there any other way than using nvidia? and if not can you guide me how can i install and use it in windows 10?

i tried without that and hence, epoch is taking a lot of time to get trained.

**Comment by arthurflor23** [comment]
Hi! Unfortunately, I don't know how. However, to use nvidia you have to install Nvidia driver + CUDA, then install TensorFlow 2.x (gpu version) in the python environment. In Windows there are more steps than Linux to set up the necessary environment, but I don't use Windows, so I don't know how to tell you more clearly what has to be done.
