### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by echu87** [arthurflor23/handwritten-text-recognition#9]
Hi Arthur, 

I first wanna say thank you for the great medium article!

I am currently trying to train a model on the bentham dataset, and I am running into an issue. 

Traceback (most recent call last):
  File "main.py", line 155, in <module>
    verbose=1)
  File "G:\Documents\GitProjects\handwritten-text-recognition-master\src\network\model.py", line 173, in fit
    use_multiprocessing=use_multiprocessing, **kwargs)
  File "C:\Users\Evan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\Evan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 224, in fit
    distribution_strategy=strategy)
  File "C:\Users\Evan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 547, in _process_training_inputs
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\Evan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 606, in _process_inputs
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\Evan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\keras\engine\data_adapter.py", line 566, in __init__
    reassemble, nested_dtypes, output_shapes=nested_shape)
  File "C:\Users\Evan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 546, in from_generator
    flattened_types = [dtypes.as_dtype(dt) for dt in nest.flatten(output_types)]
  File "C:\Users\Evan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 546, in <listcomp>
    flattened_types = [dtypes.as_dtype(dt) for dt in nest.flatten(output_types)]
  File "C:\Users\Evan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\framework\dtypes.py", line 716, in as_dtype
    return _ANY_TO_TF[type_value]
TypeError: unhashable type: 'list'

The issue occurs in main.py at model.fit(...), and subsequently in model.py at model.fit(...).

I am trying to train on my own pc (not google colab), so I am not sure if this is what is causing the error.

If you have any suggestions that would be great!

**Comment by arthurflor23** [comment]
Hi, thanks for feedback!

What is the version of libraries? I tested with python 3.7.4 and TF 2.1

**Comment by echu87** [comment]
Hi, I am currently on python 3.6.0 and TF 2.1, I will upgrade to 3.7.4 and update the thread when I test it.

**Comment by echu87** [comment]
Hi, upgrading to python 3.7.6 seems to have fixed the issue. Sorry to bother you with such a trivial problem!
